//! Tauri backend: commands exposed to the UI + persisted settings.

mod settings;

// Generated by build.rs: (name, version, license) of direct dependencies.
include!(concat!(env!("OUT_DIR"), "/third_party.rs"));

use serde::Serialize;
use settings::{Settings, SettingsStore};
use std::sync::Arc;
use tauri::{AppHandle, Manager, State};
use tauri_plugin_dialog::DialogExt;
use zsm_core::{CompatReport, DeletePlan, DeleteResult, Paths, SessionDetail, SessionSummary, Store};

#[derive(Clone)]
pub struct AppMgr {
    inner: Arc<AppInner>,
}

struct AppInner {
    settings: SettingsStore,
}

impl AppMgr {
    fn settings(&self) -> Settings {
        self.inner.settings.load()
    }

    fn store(&self) -> Result<Store, ApiError> {
        let dir = self
            .settings()
            .zcode_dir
            .or_else(|| zsm_core::Paths::default_zcode_dir().map(|p| p.to_string_lossy().to_string()))
            .ok_or_else(|| ApiError::simple("no_dir", "could not determine the ZCode data directory"))?;
        let dir = std::path::PathBuf::from(&dir);
        if !Paths::looks_valid(&dir) {
            return Err(ApiError::simple(
                "invalid_dir",
                "the configured directory does not look like a ZCode data directory",
            ));
        }
        Ok(Store::new(Paths::from_zcode_dir(&dir)))
    }
}

// ---------------- error payload ----------------

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiError {
    /// stable code the frontend maps to a localized message
    pub code: String,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub problems: Option<Vec<String>>,
}

impl ApiError {
    pub fn simple(code: &str, message: &str) -> Self {
        Self {
            code: code.into(),
            message: message.into(),
            problems: None,
        }
    }
}

impl From<zsm_core::Error> for ApiError {
    fn from(e: zsm_core::Error) -> Self {
        let (code, problems) = match &e {
            zsm_core::Error::ZcodeRunning => ("zcode_running", None),
            zsm_core::Error::Limited { violations } => (
                "limited_mode",
                Some(
                    violations
                        .iter()
                        .map(|(id, reason)| format!("{id}: {reason}"))
                        .collect(),
                ),
            ),
            zsm_core::Error::Compat { problems } => ("compat", Some(problems.clone())),
            zsm_core::Error::Corruption { details } => ("corruption", Some(details.clone())),
            zsm_core::Error::DbNotFound(_) => ("db_not_found", None),
            zsm_core::Error::Io(_) => ("io", None),
            zsm_core::Error::Sql(_) => ("sqlite", None),
            zsm_core::Error::Json(_) => ("json", None),
            zsm_core::Error::Other(_) => ("other", None),
        };
        Self {
            code: code.into(),
            message: e.to_string(),
            problems,
        }
    }
}

// ---------------- shared output types ----------------

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DbStatusOut {
    pub db: String,
    pub state: String,
    pub detail: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct AppStateOut {
    pub settings: Settings,
    pub detected_default: Option<String>,
    pub db_path: Option<String>,
    pub cli_dir: Option<String>,
    pub backups_dir: Option<String>,
    pub compat: Option<CompatReport>,
    pub zcode_running: bool,
    pub integrity: Vec<DbStatusOut>,
    pub app_version: String,
}

fn build_state(mgr: &AppMgr) -> AppStateOut {
    let settings = mgr.settings();
    let detected = Paths::default_zcode_dir();
    let dir = settings
        .zcode_dir
        .clone()
        .map(std::path::PathBuf::from)
        .or_else(|| detected.clone());
    let mut out = AppStateOut {
        settings,
        detected_default: detected.map(|p| p.to_string_lossy().to_string()),
        db_path: None,
        cli_dir: None,
        backups_dir: None,
        compat: None,
        zcode_running: zsm_core::zcode_running(),
        integrity: vec![],
        app_version: env!("CARGO_PKG_VERSION").into(),
    };
    if let Some(dir) = dir {
        if Paths::looks_valid(&dir) {
            let paths = Paths::from_zcode_dir(&dir);
            out.db_path = Some(paths.db_path.to_string_lossy().to_string());
            out.cli_dir = Some(paths.cli_dir.to_string_lossy().to_string());
            out.backups_dir = Some(zsm_core::backup::backups_base(&paths).to_string_lossy().to_string());
            out.compat = Some(zsm_core::compat::check(&paths));
            out.integrity = vec![
                DbStatusOut {
                    db: "db.sqlite".into(),
                    state: integrity_state(&paths.db_path),
                    detail: String::new(),
                },
                DbStatusOut {
                    db: "tasks-index.sqlite".into(),
                    state: integrity_state(&paths.tasks_db),
                    detail: String::new(),
                },
            ];
        }
    }
    out
}

fn integrity_state(path: &std::path::Path) -> String {
    zsm_core::integrity::check_db(path).state
}

// ---------------- commands ----------------

#[tauri::command]
async fn app_state(mgr: State<'_, AppMgr>) -> Result<AppStateOut, ApiError> {
    let mgr = mgr.inner().clone();
    tauri::async_runtime::spawn_blocking(move || Ok(build_state(&mgr)))
        .await
        .map_err(|e| ApiError::simple("join", &e.to_string()))?
}

#[tauri::command]
async fn set_zcode_dir(path: String, mgr: State<'_, AppMgr>) -> Result<AppStateOut, ApiError> {
    let dir = std::path::PathBuf::from(&path);
    if !Paths::looks_valid(&dir) {
        return Err(ApiError::simple(
            "invalid_dir",
            "the directory does not look like a ZCode data directory (need cli/db/db.sqlite or v2/tasks-index.sqlite)",
        ));
    }
    let mgr = mgr.inner().clone();
    tauri::async_runtime::spawn_blocking(move || {
        mgr.inner.settings.update(|s| {
            s.zcode_dir = Some(path.clone());
        });
        Ok(build_state(&mgr))
    })
    .await
    .map_err(|e| ApiError::simple("join", &e.to_string()))?
}

#[tauri::command]
async fn detect_zcode_dir(mgr: State<'_, AppMgr>) -> Result<AppStateOut, ApiError> {
    let mgr = mgr.inner().clone();
    tauri::async_runtime::spawn_blocking(move || {
        let detected = Paths::default_zcode_dir();
        match detected {
            Some(d) if Paths::looks_valid(&d) => {
                let val = d.to_string_lossy().to_string();
                mgr.inner.settings.update(|s| s.zcode_dir = Some(val));
            }
            _ => {
                return Err(ApiError::simple(
                    "detect_failed",
                    "could not find a ZCode data directory under the user home",
                ));
            }
        }
        Ok(build_state(&mgr))
    })
    .await
    .map_err(|e| ApiError::simple("join", &e.to_string()))?
}

#[tauri::command]
fn set_prefs(
    language: Option<String>,
    theme: Option<String>,
    idle_minutes: Option<u32>,
    poll_seconds: Option<u32>,
    mgr: State<AppMgr>,
) -> Settings {
    mgr.inner.settings.update(|s| {
        if let Some(l) = language {
            s.language = l;
        }
        if let Some(t) = theme {
            s.theme = t;
        }
        if let Some(m) = idle_minutes {
            s.idle_minutes = m.clamp(crate::settings::IDLE_MIN, crate::settings::IDLE_MAX);
        }
        if let Some(p) = poll_seconds {
            s.poll_seconds = p.clamp(crate::settings::POLL_MIN, crate::settings::POLL_MAX);
        }
    });
    mgr.settings()
}

/// Keep the native window title in sync with the UI language.
#[tauri::command]
fn set_window_title(app: AppHandle, title: String) -> Result<(), String> {
    let window = app
        .get_webview_window("main")
        .ok_or_else(|| "main window not found".to_string())?;
    window.set_title(&title).map_err(|e| e.to_string())
}

#[tauri::command]
async fn scan(mgr: State<'_, AppMgr>) -> Result<AppStateOut, ApiError> {
    let mgr = mgr.inner().clone();
    tauri::async_runtime::spawn_blocking(move || {
        // rebuild state (compat + integrity) together with the session list
        Ok(build_state(&mgr))
    })
    .await
    .map_err(|e| ApiError::simple("join", &e.to_string()))?
}

#[tauri::command]
async fn list_sessions(mgr: State<'_, AppMgr>) -> Result<Vec<SessionSummary>, ApiError> {
    let store = mgr.store()?;
    tauri::async_runtime::spawn_blocking(move || store.list_sessions().map_err(ApiError::from))
        .await
        .map_err(|e| ApiError::simple("join", &e.to_string()))?
}

#[tauri::command]
async fn session_detail(id: String, mgr: State<'_, AppMgr>) -> Result<Option<SessionDetail>, ApiError> {
    let store = mgr.store()?;
    tauri::async_runtime::spawn_blocking(move || {
        store.session_detail(&id).map_err(ApiError::from)
    })
    .await
    .map_err(|e| ApiError::simple("join", &e.to_string()))?
}

#[tauri::command]
async fn delete_plan(ids: Vec<String>, mgr: State<'_, AppMgr>) -> Result<DeletePlan, ApiError> {
    let store = mgr.store()?;
    tauri::async_runtime::spawn_blocking(move || {
        store.plan_delete(&ids).map_err(ApiError::from)
    })
    .await
    .map_err(|e| ApiError::simple("join", &e.to_string()))?
}

#[tauri::command]
async fn delete_execute(ids: Vec<String>, mgr: State<'_, AppMgr>) -> Result<DeleteResult, ApiError> {
    let store = mgr.store()?;
    // limited mode applies only while ZCode is running (core checks that itself)
    let idle_minutes = mgr.settings().idle_minutes_clamped();
    tauri::async_runtime::spawn_blocking(move || {
        let policy = zsm_core::RunningPolicy::Limited { idle_minutes };
        store.execute_delete_with_policy(&ids, policy).map_err(ApiError::from)
    })
    .await
    .map_err(|e| ApiError::simple("join", &e.to_string()))?
}

#[tauri::command]
async fn pick_folder(app: AppHandle) -> Result<Option<String>, ApiError> {
    tauri::async_runtime::spawn_blocking(move || {
        let picked = app.dialog().file().blocking_pick_folder();
        Ok(picked.map(|p| p.to_string()))
    })
    .await
    .map_err(|e| ApiError::simple("join", &e.to_string()))?
}

#[tauri::command]
fn reveal_path(path: String) -> Result<(), String> {
    #[cfg(target_os = "windows")]
    {
        std::process::Command::new("explorer")
            .arg(&path)
            .spawn()
            .map_err(|e| e.to_string())?;
    }
    #[cfg(not(target_os = "windows"))]
    {
        let _ = path;
    }
    Ok(())
}

/// (name, version, license) of direct dependencies, generated by build.rs.
#[tauri::command]
fn third_party() -> Vec<(String, String, String)> {
    THIRD_PARTY
        .iter()
        .map(|(n, v, l)| (n.to_string(), v.to_string(), l.to_string()))
        .collect()
}

#[tauri::command]
fn third_party_generated() -> bool {
    THIRD_PARTY_GENERATED
}

/// CHANGELOG.md bundled at compile time so the in-app release notes always
/// match the repository.
#[tauri::command]
fn changelog_text() -> String {
    include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/../CHANGELOG.md")).to_string()
}

/// Open an https URL in the system browser.
#[tauri::command]
fn open_external(url: String) -> Result<(), String> {
    if !url.starts_with("https://") {
        return Err("only https:// urls are allowed".into());
    }
    #[cfg(target_os = "windows")]
    {
        use std::os::windows::process::CommandExt;
        std::process::Command::new("cmd")
            .args(["/C", "start", "", &url])
            .creation_flags(0x0800_0000) // CREATE_NO_WINDOW
            .spawn()
            .map_err(|e| e.to_string())?;
    }
    #[cfg(not(target_os = "windows"))]
    {
        let _ = url;
    }
    Ok(())
}

/// Lightweight ZCode process probe for UI polling (the authoritative check
/// still happens inside delete_execute).
#[tauri::command]
fn is_zcode_running() -> bool {
    zsm_core::zcode_running()
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .manage(AppMgr {
            inner: Arc::new(AppInner {
                settings: SettingsStore::new(),
            }),
        })
        .invoke_handler(tauri::generate_handler![
            app_state,
            set_zcode_dir,
            detect_zcode_dir,
            set_prefs,
            set_window_title,
            scan,
            list_sessions,
            session_detail,
            delete_plan,
            delete_execute,
            pick_folder,
            reveal_path,
            third_party,
            third_party_generated,
            changelog_text,
            open_external,
            is_zcode_running
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
